FROM condaforge/mambaforge:latest
LABEL io.github.snakemake.containerized="true"
LABEL io.github.snakemake.conda_env_hash="c172cd88bfa3e8ab3b9c4082e1db8420db01c62b558fa055549b7ce063a1bf4c"

# Step 1: Retrieve conda environments

# Conda environment:
#   source: envs/busco_trees.yml
#   prefix: /conda-envs/35e044aa308b793ed754eda9201dd16e
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - busco
#     - mafft
#     - prank
#     - clustalw
#     - ruby
#     - perl
#     - perl-bioperl
#     - raxml
RUN mkdir -p /conda-envs/35e044aa308b793ed754eda9201dd16e
COPY envs/busco_trees.yml /conda-envs/35e044aa308b793ed754eda9201dd16e/environment.yaml

# Step 2: Generate conda environments

RUN mamba env create --prefix /conda-envs/35e044aa308b793ed754eda9201dd16e --file /conda-envs/35e044aa308b793ed754eda9201dd16e/environment.yaml && \
    mamba clean --all -y

RUN apt-get update && \
    apt-get install -y build-essential

RUN wget https://github.com/stamatak/standard-RAxML/archive/v8.2.12.tar.gz && \
  tar -xvf v8.2.12.tar.gz && \
  rm -rf v8.2.12.tar.gz && \
  cd standard-RAxML-8.2.12/ && \
  make -f Makefile.gcc && \
  rm *.o && \
  make -f Makefile.SSE3.gcc && \
  rm *.o && \
  make -f Makefile.AVX.gcc && \
  rm *.o && \
  make -f Makefile.PTHREADS.gcc && \
  rm *.o && \
  make -f Makefile.SSE3.PTHREADS.gcc && \
  rm *.o && \
  make -f Makefile.AVX.PTHREADS.gcc && \
  rm *.o

  ENV PATH="${PATH}:/standard-RAxML-8.2.12"