FROM condaforge/mambaforge:latest
LABEL io.github.snakemake.containerized="true"
LABEL io.github.snakemake.conda_env_hash="669b586d53f499be7121792fdb1484a5bdc10a3e9ecbcecb947219dce123a0b1"

# Step 1: Retrieve conda environments

# Conda environment:
#   source: envs/HIFI.yml
#   prefix: /conda-envs/a0d6761188ddadf1da8975c8bb124467
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - hifiasm
RUN mkdir -p /conda-envs/a0d6761188ddadf1da8975c8bb124467
COPY envs/HIFI.yml /conda-envs/a0d6761188ddadf1da8975c8bb124467/environment.yaml

# Conda environment:
#   source: envs/busco.yml
#   prefix: /conda-envs/d953ec62a74eda759247fd41ebac6950
#   name: busco
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - busco == 5.2.2
RUN mkdir -p /conda-envs/d953ec62a74eda759247fd41ebac6950
COPY envs/busco.yml /conda-envs/d953ec62a74eda759247fd41ebac6950/environment.yaml

# Conda environment:
#   source: envs/flye.yml
#   prefix: /conda-envs/335f355511bdf680225afd96118772ed
#   name: busco
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - flye == 2.9
RUN mkdir -p /conda-envs/335f355511bdf680225afd96118772ed
COPY envs/flye.yml /conda-envs/335f355511bdf680225afd96118772ed/environment.yaml

# Conda environment:
#   source: envs/mini.yml
#   prefix: /conda-envs/2b00d729406c09d5f1e2da89a4b9ad02
#   name: mini
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - medaka == 1.4.3
#     - pilon == 1.24
#     - racon == 1.4.20
#     - minimap2 == 2.21
#     - miniasm == 0.3_r179
#     - samtools
#     - purge_haplotigs
RUN mkdir -p /conda-envs/2b00d729406c09d5f1e2da89a4b9ad02
COPY envs/mini.yml /conda-envs/2b00d729406c09d5f1e2da89a4b9ad02/environment.yaml

# Conda environment:
#   source: envs/spades.yml
#   prefix: /conda-envs/e80d9865919491b14955c31689aec7da
#   name: busco
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - spades == 3.15.2
RUN mkdir -p /conda-envs/e80d9865919491b14955c31689aec7da
COPY envs/spades.yml /conda-envs/e80d9865919491b14955c31689aec7da/environment.yaml

# Conda environment:
#   source: envs/wtdbg.yml
#   prefix: /conda-envs/55fa03f14dd730b77f8875ed0bfe7f51
#   name: busco
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - wtdbg == 2.5
RUN mkdir -p /conda-envs/55fa03f14dd730b77f8875ed0bfe7f51
COPY envs/wtdbg.yml /conda-envs/55fa03f14dd730b77f8875ed0bfe7f51/environment.yaml

# Step 2: Generate conda environments

RUN mamba env create --prefix /conda-envs/a0d6761188ddadf1da8975c8bb124467 --file /conda-envs/a0d6761188ddadf1da8975c8bb124467/environment.yaml && \
    mamba env create --prefix /conda-envs/d953ec62a74eda759247fd41ebac6950 --file /conda-envs/d953ec62a74eda759247fd41ebac6950/environment.yaml && \
    mamba env create --prefix /conda-envs/335f355511bdf680225afd96118772ed --file /conda-envs/335f355511bdf680225afd96118772ed/environment.yaml && \
    mamba env create --prefix /conda-envs/2b00d729406c09d5f1e2da89a4b9ad02 --file /conda-envs/2b00d729406c09d5f1e2da89a4b9ad02/environment.yaml && \
    mamba env create --prefix /conda-envs/e80d9865919491b14955c31689aec7da --file /conda-envs/e80d9865919491b14955c31689aec7da/environment.yaml && \
    mamba env create --prefix /conda-envs/55fa03f14dd730b77f8875ed0bfe7f51 --file /conda-envs/55fa03f14dd730b77f8875ed0bfe7f51/environment.yaml && \
    mamba clean --all -y
