FROM condaforge/mambaforge:latest
LABEL io.github.snakemake.containerized="true"
LABEL io.github.snakemake.conda_env_hash="8eea06161935a86a9d07ff5de44d79371fae31d3c310b75e4b31909aaab29efb"

# Step 1: Retrieve conda environments

# Conda environment:
#   source: envs/busco_trees.yml
#   prefix: /conda-envs/b0c8294c423c389b94d1272a93ee6c64
#   channels:
#     - conda-forge
#     - bioconda
#     - defaults
#   dependencies:
#     - busco
#     - mafft
#     - perl-bioperl
#     - raxml
RUN mkdir -p /conda-envs/b0c8294c423c389b94d1272a93ee6c64
COPY envs/busco_trees.yml /conda-envs/b0c8294c423c389b94d1272a93ee6c64/environment.yaml

# Step 2: Generate conda environments

RUN mamba env create --prefix /conda-envs/b0c8294c423c389b94d1272a93ee6c64 --file /conda-envs/b0c8294c423c389b94d1272a93ee6c64/environment.yaml && \
    mamba clean --all -y

RUN apt-get update && \
    apt-get install -y build-essential

RUN wget https://github.com/stamatak/standard-RAxML/archive/v8.2.12.tar.gz && \
  tar -xvf v8.2.12.tar.gz && \
  rm -rf v8.2.12.tar.gz && \
  cd standard-RAxML-8.2.12/ && \
  make -f Makefile.gcc && \
  rm *.o && \
  make -f Makefile.SSE3.gcc && \
  rm *.o && \
  make -f Makefile.AVX.gcc && \
  rm *.o && \
  make -f Makefile.PTHREADS.gcc && \
  rm *.o && \
  make -f Makefile.SSE3.PTHREADS.gcc && \
  rm *.o && \
  make -f Makefile.AVX.PTHREADS.gcc && \
  rm *.o

  ENV PATH="${PATH}:/standard-RAxML-8.2.12